### ISSUE TITLE
Looks like mistake in the code #1836

### ISSUE THREAD

**Issue by kachurk** [fishercoder1534/Leetcode#180]
Current implementation will return only one element in all cases.
Fix is to skip duplicates and stay only unique elements. Fix attached to this issue. 
<img width="982" alt="Screenshot 2023-12-12 at 12 14 57" src="https://github.com/fishercoder1534/Leetcode/assets/7191668/6309436c-a4ef-441b-8be6-d7d1231471f0">

**Comment by fishercoder1534** [comment]
Please submit a merge-able PR instead of opening an issue, thanks!
