### ISSUE TITLE
In 724, why pivot index = 0 is a valid solution? 

### ISSUE THREAD

**Issue by surajwy** [fishercoder1534/Leetcode#22]
Hi,

Can you please share your thoughts on why pivot index = 0 is a right answer?
I can see that in your solution at [this line](https://github.com/fishercoder1534/Leetcode/blob/master/src/main/java/com/fishercoder/solutions/_724.java#L44), you have purposely coded this condition (the first condition of OR construct).

The case for which this happens is:
```
[ -1, -1, -1, 0, 1, 1]
```

Would request you to reply over [this discussion thread](https://leetcode.com/problems/find-pivot-index/discuss/136167/This-is-a-very-poorly-described-problem) and share your thoughts. Lot of people are having same doubt.

Thanks.

**Comment by fishercoder1534** [comment]
Thanks a lot for opening an issue here. It's been a while I logged into Leetcode.
I just replied to that thread.
Happy coding! ^_^
