### ISSUE TITLE
#401 Binary Watch has an incorrect solution

### ISSUE THREAD

**Issue by jimsmithm3** [fishercoder1534/Leetcode#38]
When you run it against the provided test case it even fails

Input 
1

Output
["0:01","0:02","0:04","0:08","0:16","0:32","1:04","2:08","4:16","8:32"]
Expected
["0:01","0:02","0:04","0:08","0:16","0:32","1:00","2:00","4:00","8:00"]

You can't treat hour like 60 minutes here, it's not a regular clock.

**Comment by fishercoder1534** [comment]
Great call! Thanks for pointing it out, I've fixed it and added a test to verify it.
