### ISSUE TITLE
Main Page link for 434 solution is a "404 page" 

### ISSUE THREAD

**Issue by jimsmithm3** [fishercoder1534/Leetcode#39]
The URL is currently to the problem name for this one not the # .  _434

**Comment by fishercoder1534** [comment]
Great find! I just fixed it. Thanks!

**Comment by jimsmithm3** [comment]
@fishercoder1534 

Looking at the page source found these as well. 
Pretty sure the same issue as above.

146
163
174
200
485
496
503
539
556

**Comment by sunstev-amzn** [comment]
I just fixed them, thanks a lot for checking! :)
