### ISSUE TITLE
_325 Maximum Size Subarray Sum Equals k

### ISSUE THREAD

**Issue by dhiralpandya** [fishercoder1534/Leetcode#63]
Hi @fishercoder1534  

I think solution for _325 would not work for below input 

{1,3,7,2} and Sum 5 

Expected output **{2,3} = 2** but solution is giving **0**

Let me know your suggestion on this. :)

**Comment by shreyanshi2228** [comment]
HEY !! Can I take this issue?

**Comment by Luv8436** [comment]
hey please accept my first ever pr and merge it after reviewing it.

**Comment by deepakjsr25** [comment]
Hey ! Is this issue still open?

**Comment by fishercoder1534** [comment]
Hi @dhiralpandya , if you think this is a valid test case, please submit it to LeetCode first. So far, this solution is AC'ed on LeetCode. Thanks!
